### ISSUE TITLE
Unable to extract files from ZSTD compressed packages

### ISSUE THREAD

**Issue by CubeTheThird** [5long/p3wm#13] opened 2022-08-11 17:52 UTC
It seems as of late I have trouble using this utility. When attempting to verify a pacnew, error messages appear indicating that the source package is not a valid tar. I suspect this is a result of the move towards using tar.zst packages. Regardless, this prevents auto merges from being attempted.

**Comment by 5long** [comment] 2022-09-25 07:46
p3wm only matches package files by `.pkg.*`, which shouldn't exclude .zst files. See [find_cached_pkg in 0.6.3](https://github.com/5long/p3wm/blob/v0.6.3/bin/p3wm#L154-L174)

This issue might be caused by taking .sig files as packages. Now it should be fixed by [this pull request](https://github.com/5long/p3wm/pull/12) (which was opened a whole year ago).

I'll release a 0.6.x soon-ish to include the formentioned pull request.

**Comment by 5long** [comment] 2022-09-25 09:19
Released 0.7.0 on AUR.

**Closed as completed** 2022-09-25 09:19 UTC
